name: Fetch blog RSS and convert to markdown

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch: # allow manual run

jobs:
  fetch-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install feedparser
        run: pip install feedparser

      - name: Fetch RSS and convert to markdown
        run: |
          python scripts/rss_to_md.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add rss-posts/
          git commit -m "Add new RSS posts" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/psbrandlab/plantbagh.git
          git push origin main
